# Generated by Django 5.2.4 on 2025-07-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('task', '0003_task_due_at_task_remind_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='task',
        ),
        migrations.AddField(
            model_name='contact',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='task.task', verbose_name='Task'),
        ),
    ]
