# Generated by Django 5.2.4 on 2025-07-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_task_contact_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='task',
            new_name='tasks',
        ),
    ]
