# Generated by Django 5.2.4 on 2025-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_task_contact_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
    ]
