# Generated by Django 5.2.4 on 2025-08-02 07:35

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ImageField(blank=True, default='default.png', upload_to='Profiles', validators=[contact.models.profile_size_validator], verbose_name='Profile Picture'),
        ),
    ]
