# Generated by Django 5.2.4 on 2025-07-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_created_at_alter_tag_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='test', max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
