# Generated by Django 5.2.4 on 2025-07-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('project', models.CharField(blank=True, max_length=50, null=True, verbose_name='Project')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is done')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('completed_at', models.DateTimeField(verbose_name='Completed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='task_task_created_e28b08_idx'), models.Index(fields=['-completed_at'], name='task_task_complet_dce5db_idx')],
            },
        ),
    ]
