# Generated by Django 5.2.4 on 2025-07-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected to finish at'),
        ),
        migrations.AddField(
            model_name='task',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Remind at'),
        ),
    ]
