# Generated by Django 5.2.4 on 2025-07-25 07:02

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[user.models.phone_validator], verbose_name='Phone number'),
        ),
    ]
